name: Bug report
description: Report a reproducible bug
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened? Include error text if any.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Steps to reproduce (numbered).
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/recording (optional)
      description: Attach screenshots or a short recording if helpful.
    validations:
      required: false
  - type: input
    id: node
    attributes:
      label: Node version
      placeholder: e.g. 20.19.5
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: e.g. macOS 14 / Windows 11 / Ubuntu 22.04
    validations:
      required: false
